name: test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Setup Mongo
        uses: 280780363/mongo-action@v0.4
      - name: Test
        run: dotnet test ./src/Shashlik.EventBus.sln